import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nabvar from "@/Components/Nabvar";
import { Toaster } from "react-hot-toast";
import NextauthProvider from "@/Provider/NextauthProvider";
import QueryProvider from "@/Components/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >

      <body className="min-h-full flex flex-col">
        <QueryProvider>
        <NextauthProvider>
          <Nabvar></Nabvar>
          <Toaster></Toaster>
          {children}
        </NextauthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
